version: '3'
services:
  node:
    image: "node:8"
    volumes:
      - ".:/usr/src/app"
    environment:
      DEBUG: "gmtarr:*"
      HOST: "0.0.0.0"
      PORT: "8080"
      # pass API_BASE_URL from calling shell environment
      API_BASE_URL:
    ports:
      - "8080:8080"
    working_dir: "/usr/src/app"
    command: [npm, start]
